### ISSUE TITLE
could you please change the min android api level? 

### ISSUE THREAD

**Issue by xueqingxiao** [oguzbabaoglu/butterfork#4]
Variant Debug has a dependency on version 4.1.1.4 of the legacy com.google.android Maven artifact, which corresponds to API level 15. This is not compatible with min SDK of this module, which is 14.

**Comment by oguzbabaoglu** [comment]
Which minSdk are you referring to? The modules are java modules, no minSdk is set. The samples use minSdk 16.

Butterknife changed to `minSdkVersion 8`, same can be done for this by using `com.google.android:android:2.1.2`

**Comment by xueqingxiao** [comment]
@oguzbabaoglu android 2.3 is ok, Thanks a lot.

**Comment by oguzbabaoglu** [comment]
Fixed with update to ButterKnife 8.0.1
